[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100

[environments.production.variables]
NODE_ENV = "production"
JWT_SECRET = "moedim-super-secret-jwt-key-production-5785"
CORS_ORIGIN = "*"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"